apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{values.name}}
  description: The virtual machine for the ${{values.stack}}
  links:
  - title: GitLab Console
    url: https://gitlab.com/soeldnerconsult1
spec:
  type: virtual-machine
  owner: ${{values.owner | dump}}
  lifecycle: experimental
  system: ${{values.system}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: hallo

spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: ${{values.system}}
  dependsOn:
  - resource:default/${{values.name}}